### ISSUE TITLE
Multipose

### ISSUE THREAD

**Issue by MarcelKlammer** [labofoz/handsfree.js#64]
Hi Oz,

just saw your v4.1.0 release:
https://github.com/labofoz/handsfree.js/releases/tag/4.1.0

Just a hint: you could setNumFacesToTrack to the number of found posenet bodies, if you really want to have it dynamically... but be aware, that more faces means less performance ...

Cheers
Marcel

**Comment by labofoz** [comment]
Thanks Marcel! setNumFacesToTrack is now working for brf too, I didn't have someone around to test so I sketched a face brf can track to test 2 cursors at once:

![ezgif com-optimize 5](https://user-images.githubusercontent.com/42591975/52433356-c1ccf400-2ac1-11e9-83bc-d46026faf13f.gif)

Setting two faces can now be done by instantiating with maxPoses:

```js
handsfree = new Handsfree({settings: {maxPoses: 2}})
handsfree.start()
```
